### ISSUE TITLE
Hapi throws error while registering "inert"

### ISSUE THREAD

**Issue by rootcss** [hapijs/inert#105]
Hey,

Here's my server.js file:
```
var Hapi = require('hapi');
var Path = require('path');

var server = new Hapi.Server();
server.connection({ 
  host: 'localhost',
  port: 8001 
});

server.register(require('inert'), (err) => {

  if (err) {
    throw err;
  }

  server.route({
    method: 'GET',
    path: '/{param*}',
    handler: {
      directory: {
        path: 'public'
      }
    }
  });


  server.start((err) => {

    if (err) {
      throw err;
    }

    console.log('Server running at:', server.info.uri);
  });
});
```

I am getting following error while starting the server:
```
/Users/rootcss/test/node_modules/hapi/lib/plugin.js:211
        if (plugin.register.register) {                             // Required plugin
                            ^

TypeError: Cannot read property 'register' of undefined
    at module.exports.internals.Server.internals.Plugin.register (/Users/rootcss/test/node_modules/hapi/lib/plugin.js:211:29)
    at Object.<anonymous> (/Users/rootcss/test/server2.js:10:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
Additionally, all examples from Hapi's website are also failing with the same error. Am I making some fundamental mistake or it's some version specific issue?

Node v8.9.0 | Hapi v16.6.2 | Inert v5.0.1 | MacOS 10.12.6

**Comment by WesTyler** [comment]
Inert version 5.x has breaking changes for hapi v17 support. That means for hapi 16 like you are using you will need to use Inert v4.x ; or, to use Inert v5 you will need to update to hapi v17 (lots of breaking changes).

**Comment by WesTyler** [comment]
Inert v5 [release notes](https://github.com/hapijs/inert/issues/100)

and hapi v17 [release notes](https://github.com/hapijs/hapi/issues/3658)

**Comment by rootcss** [comment]
Thank you. Setting Inert to version "^4.2.1", worked.
