### ISSUE TITLE
Util.promisify is not a function -- when trying to serve static files

### ISSUE THREAD

**Issue by konstantinB1** [hapijs/inert#112]
Hi. Im new to Hapi, so i followed instructions from website exactly as told but nevertheless it keeps throwing this error.
```
TypeError: Util.promisify is not a function
    at Object.<anonymous> (C:\projects\master-nodejs\node_modules\inert\lib\fs.js:117:28)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\projects\master-nodejs\node_modules\inert\lib\file.js:14:12)
    at Module._compile (module.js:571:32)
```
Tried both on Hapi v16, and v17. It works well when until i inttroduce the inert plugin for static files. 
This is literally a copy-paste from here:

```
const Hapi = require('hapi');
const inert = require('inert');

const server = new Hapi.Server();

server.connection({port: 3000, host: 'localhost'});

const provision = async () => {

	await server.register(inert);

    server.route({
        method: 'GET',
        path: '/{param*}',
        handler: {
            directory: {
                path: '.',
                redirectToSlash: true,
                index: true,
            }
        }
    });
	await server.start();
}


```
From youtube tutorial, that is almost the same as official Hapi documentation
```
// Old attempt
server.register(require('inert'), (err) => {
	if (err) throw err;

	server.route({
		method: 'GET',
		path: '/file.js',
		handler: (req, res) => {
	        res.file('public/js/myfile.js');
		}
	})

	server.start((err) => {
		if (err) throw err;
	})
});
```
Also tried changing inert versions, without much success. Am i doing something wrong ?

**Comment by Marsup** [comment]
Your node version is likely wrong, you must use 8+.

**Comment by gojoin** [comment]
upgrade nodejs from v6.14.3 to v11.6.0.   It works now! Thanks!
