### ISSUE TITLE
Error catching the directory handler

### ISSUE THREAD

**Issue by zveljkovic** [hapijs/inert#128]
Hello,

How can we catch errors from directory handler?

I have this bit of code 
```
this.server.route({
	method: 'GET',
	path: '/admin/{param*}',
	handler: {
		directory: {path: 'public/admin'},
	},
});
```
and it immediately responds with  
``` 
{
    "statusCode": 404,
    "error": "Not Found",
    "message": "Not Found"
}
```

We have global error handler attached to `this.server.ext('onPreResponse', this.globalErrorHandler.onPreResponse);` but it is not called...

**Comment by hueniverse** [comment]
`onPreResponse` should always be called so there is probably something else going on in your setup. Can you create a working example for this?

**Comment by zveljkovic** [comment]
I am sorry for not looking in this properly. I had one other call to onPreResponse that was called first.
Any way we can not log error happening?
```
Debug: handler, error
  Error: Not Found
  at exports.File.open (...\node_modules\@hapi\inert\lib\fs.js:37:24)
```

**Comment by hueniverse** [comment]
I don't know what you are seeing...

**Comment by zveljkovic** [comment]
Hi again, 
I finally got the time to reproduce the issue I had with logging. This was not an issue on inert side but my mistake and convoluted configuration on server. You can close this issue. Just if anyone has the same problem that whenever Not Found error is generated, and fills the console output please check the debug.request server settings. 

I had this code
```
const {Server} = require('@hapi/hapi');
const Inert = require('@hapi/inert');
const Boom = require('@hapi/boom');
async function start() {
    const server = new Server({
        port: 80,
        host: 'localhost',
        debug: {
            request: ['error'],
        },
    });

    await server.register(Inert);

    server.ext('onPreResponse', (request, h) => {
        return h.file('public/admin/index.html');
    });

    server.route({
        method: 'GET',
        path: '/admin/{param*}',
        handler: {
            directory: {
                path: 'public/admin',
            },
        },
    });
    await server.start();
}
start();
```

Here debug.request is being enabled for errors and that outputed the following in the console
```
Debug: handler, error
    Error: Not Found
    at exports.File.open (C:\Users\zvelj\Desktop\ss\InertIssue\node_modules\@hapi\inert\lib\fs.js:37:24)
```

If you remove this setting it doesn't output error message.

Sorry again for making this issue. I should be more considerate and provide the reproducible example.
