### ISSUE TITLE
Invalid "inert" server options issue after Hapi update to 20.2.2 :

### ISSUE THREAD

**Issue by yogeesh-lilly** [hapijs/inert#165]
```
[1]         const settings = Validate.attempt(server.settings.plugins?.inert ?? {}, internals.schema, 'Invalid "inert" server options');
[1]                                                                   ^
[1] 
[1] SyntaxError: Unexpected token '.'
[1]     at wrapSafe (internal/modules/cjs/loader.js:915:16)
[1]     at Module._compile (internal/modules/cjs/loader.js:963:27)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[1]     at Module.load (internal/modules/cjs/loader.js:863:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[1]     at Module.require (internal/modules/cjs/loader.js:887:19)
[1]     at require (internal/modules/cjs/helpers.js:74:18)
[1]     at Object.<anonymous> (/Users/c305174/Projects/DIGH_LC3_CONFIGURATION_PORTAL_V2/server/config/manifest.js:1:15)
[1]     at Module._compile (internal/modules/cjs/loader.js:999:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

#### Context

Node: 12.20.2
npm: 6.14.11
hapi: 20.2.2
 inert: 7.0.0
What am I doing wrong?

**Comment by devinivy** [comment]
Interesting— this optional chaining syntax is supported in node v14: https://node.green/#ES2020-features-optional-chaining-operator-----

What is the specific version of nodejs you're using?  And are you getting the exact same error, or a new one?

**Comment by yogeesh-lilly** [comment]
HI @devinivy 

I am getting new error:

`[1] /Users/c305174/Projects/DIGH_LC3_CONFIGURATION_PORTAL_V2/node_modules/@hapi/hoek/lib/assert.js:21
[1]     throw new AssertError(args);
[1]     ^
[1] 
[1] Error: Method no longer accepts array arguments: valid
[1]     at new module.exports (/Users/c305174/Projects/DIGH_LC3_CONFIGURATION_PORTAL_V2/node_modules/@hapi/hoek/lib/error.js:23:19)
[1]     at module.exports (/Users/c305174/Projects/DIGH_LC3_CONFIGURATION_PORTAL_V2/node_modules/@hapi/hoek/lib/assert.js:21:11)
[1]     at exports.verifyFlat (/Users/c305174/Projects/DIGH_LC3_CONFIGURATION_PORTAL_V2/node_modules/joi/lib/common.js:214:9)
[1]     at internals.Base.valid (/Users/c305174/Projects/DIGH_LC3_CONFIGURATION_PORTAL_V2/node_modules/joi/lib/base.js:297:16)
[1]     at Object.<anonymous> (/Users/c305174/Projects/DIGH_LC3_CONFIGURATION_PORTAL_V2/server/validations/request/createAppRequest.js:6:22)
[1]     at Module._compile (node:internal/modules/cjs/loader:1120:14)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
[1]     at Module.load (node:internal/modules/cjs/loader:998:32)
[1]     at Module._load (node:internal/modules/cjs/loader:839:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1022:19)`

**Comment by devinivy** [comment]
This error is unrelated to inert: check-out the "joi Schema Compiler" section in the hapi v19 release notes for more information: https://github.com/hapijs/hapi/issues/4017
