### ISSUE TITLE
auth: false

### ISSUE THREAD

**Issue by jekka-ua** [hapijs/inert#40]
Is it possible to use auth (for example "auth: false") for "directory" handler in principle ?

**Comment by hueniverse** [comment]
Did you try and failed or just don't want to try?

**Comment by jekka-ua** [comment]
i tried to use 'auth' option in route and handler objects but without success and in case of directory object
```javascript
      {
            method: 'GET',
            path: '/{param*}',
            handler: {
                directory: {
                    auth:false,
                    path: path.join(config.root, 'public'),
                    listing: false
                }
            }
        },
```
i got
`[1] "auth" is not allowed`

So i'm wondering is this a feature or bug or shortcoming.

**Comment by johnbrett** [comment]
You just have the `auth` property at the wrong level. Your handler should look like this:

````javascript
{
    method: 'GET',
    path: '/{param*}',
    config: {
        handler: {
            directory: {
                path: path.join(config.root, 'public'),
                listing: false
            }
        },
        auth:false,
    }
},
````

**Comment by jekka-ua** [comment]
In this case there is the error . My Hapi is 9.3.1

Just in case the whole message:
```
user@xxxx:/var/www/xxxx$ NODE_ENV='development' node server
version 1.0.0
node env development
/var/www/xxxx/node_modules/hapi/node_modules/hoek/lib/index.js:723
    throw new Error(msgs.join(' ') || 'Unknown error');
          ^
Error: Invalid routeConfig options (/{param*}) {
  "cache": {
    "statuses": [
      200
    ]
  },
  "cors": {
    "origin": [
      "*"
    ],
    "isOriginExposed": true,
    "matchOrigin": true,
    "maxAge": 86400,
    "headers": [
      "Authorization",
      "Content-Type",
      "If-None-Match"
    ],
    "additionalHeaders": [],
    "methods": [
      "GET",
      "HEAD",
      "POST",
      "PUT",
      "PATCH",
      "DELETE",
      "OPTIONS"
    ],
    "additionalMethods": [],
    "exposedHeaders": [
      "WWW-Authenticate",
      "Server-Authorization"
    ],
    "additionalExposedHeaders": [],
    "credentials": false,
    "override": true
  },
  "files": {
    "relativeTo": "."
  },
  "json": {
    "replacer": null,
    "space": null,
    "suffix": null
  },
  "payload": {
    "failAction": "error",
    "maxBytes": 1048576,
    "output": "data",
    "parse": true,
    "timeout": 10000,
    "uploads": "/tmp",
    "defaultContentType": "application/json"
  },
  "response": {
    "options": {}
  },
  "security": null,
  "state": {
    "parse": true,
    "failAction": "error"
  },
  "timeout": {
    "server": false
  },
  "validate": {
    "options": {}
  },
  "handler" [1, 2, 3]: {
    "directory": {
      "path": "/var/www/xxxx/public",
      "listing": false
    },
    "auth": false
  }
}

[1] "handler" must be a Function
[2] "handler" must be a string
[3] "handler" must have 1 children
    at Object.exports.assert (/var/www/xxxx/node_modules/hapi/node_modules/hoek/lib/index.js:723:11)
    at Object.exports.assert (/var/www/xxxx/node_modules/hapi/lib/schema.js:15:10)
    at new module.exports.internals.Route (/var/www/xxxx/node_modules/hapi/lib/route.js:54:12)
    at internals.Connection._addRoute (/var/www/xxxx/node_modules/hapi/lib/connection.js:361:17)
    at internals.Connection._route (/var/www/xxxx/node_modules/hapi/lib/connection.js:353:18)
    at internals.Plugin._apply (/var/www/xxxx/node_modules/hapi/lib/plugin.js:503:14)
    at internals.Plugin.route (/var/www/xxxx/node_modules/hapi/lib/plugin.js:476:10)
    at /var/www/xxxx/server/index.js:44:16
    at /var/www/xxxx/node_modules/hapi/lib/plugin.js:261:16
    at done (/var/www/xxxx/node_modules/hapi/node_modules/items/lib/index.js:30:25)
    at Object.exports.register (/var/www/xxxx/server/plugins/auth/index.js:39:5)
    at Items.serial.self.root._registring (/var/www/xxxx/node_modules/hapi/lib/plugin.js:257:14)
    at iterate (/var/www/xxxx/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/var/www/xxxx/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at Object.exports.register (/var/www/xxxx/node_modules/hapi-cache-buster/lib/index.js:27:12)
    at Items.serial.self.root._registring (/var/www/xxxx/node_modules/hapi/lib/plugin.js:257:14)
```

**Comment by jekka-ua** [comment]
Thank you for your help !
