### ISSUE TITLE
Error: Invalid plugin options {}

### ISSUE THREAD

**Issue by delvedor** [hapijs/inert#46]
Hi all!
I am approaching for the first time to Hapi, and I wrote my first server code following the tutorial without any kind of problems.

Now I'm trying to add `inert` for load a static html file, but I get this error.
```
delvedor$ npm run server

> app@0.0.0 server /Users/delvedor/Development/app
> node server.js

/Users/delvedor/Development/app/node_modules/hapi/node_modules/hoek/lib/index.js:731
    throw new Error(msgs.join(' ') || 'Unknown error');
    ^

Error: Invalid plugin options {}

[1] "once" is not allowed
    at Object.exports.assert (/Users/delvedor/Development/app/node_modules/hapi/node_modules/hoek/lib/index.js:731:11)
    at Object.exports.assert (/Users/delvedor/Development/app/node_modules/hapi/lib/schema.js:15:10)
    at internals.Plugin.register (/Users/delvedor/Development/app/node_modules/hapi/lib/plugin.js:221:25)
    at Object.<anonymous> (/Users/delvedor/Development/app/server.js:20:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
```
Following my server code:
```javascript
'use strict';

const Hapi = require('hapi');

const server = new Hapi.Server();

server.connection({
  host: 'localhost',
  port: 3000
});

server.register([require('inert'), {
  register: require('good'),
  options: {
    reporters: [{
      reporter: require('good-console'),
      events: {
        response: '*',
        log: '*'
      }
    }]
  }
}], function(err) {
  if (err)
    console.error('Failed to load plugin:', err);

  server.start(() => {
    server.log('info', `Server running at: ${server.info.uri}`);
  });
});

server.route({
  method: 'GET',
  path: '/{param*}',
  handler: {
    directory: {
      path: 'public',
      index: ['index.html']
    }
  }
});
```
Node: v4.1.2
npm: v2.14.4
hapi: v10.3.0
inert: v3.1.0

What am I doing wrong?
(I get the same error following the docs inside the inert readme)

**Comment by kanongil** [comment]
You need to use Hapi 10.4+.

**Comment by delvedor** [comment]
That was easy :grin:
Thanks!
