### ISSUE TITLE
Error: Unknown handler: directory

### ISSUE THREAD

**Issue by smahi** [hapijs/inert#80]
Hi,
I am using inert to serve static content, but unfortunately it is not working properly, instead i am getting the following error : 

`Error: Unknown handler: directory
    at Object.exports.assert (/Users/smahi/Sites/HapiJS_Projects/rassif-imar.com/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.defaults (/Users/smahi/Sites/HapiJS_Projects/rassif-imar.com/node_modules/hapi/lib/handler.js:111:14)
    at new module.exports.internals.Route (/Users/smahi/Sites/HapiJS_Projects/rassif-imar.com/node_modules/hapi/lib/route.js:60:37)
    at internals.Connection._addRoute (/Users/smahi/Sites/HapiJS_Projects/rassif-imar.com/node_modules/hapi/lib/connection.js:411:19)
    at internals.Connection._route (/Users/smahi/Sites/HapiJS_Projects/rassif-imar.com/node_modules/hapi/lib/connection.js:403:18)
    at internals.Plugin._apply (/Users/smahi/Sites/HapiJS_Projects/rassif-imar.com/node_modules/hapi/lib/plugin.js:588:14)
    at internals.Plugin.route (/Users/smahi/Sites/HapiJS_Projects/rassif-imar.com/node_modules/hapi/lib/plugin.js:558:10)
    at Object.<anonymous> (/Users/smahi/Sites/HapiJS_Projects/rassif-imar.com/server.js:15:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
`

even though i properly setup the plugin and the route.

```js
{
        method: 'GET',
        path: '/{param*}',
        handler: {
            directory: {
                path: './public',
                redirectToSlash: true,
                index: true
            }
        }
    }
```

```js
{
        register: require('inert')
 }
```

Did i miss something important ?

**Comment by Marsup** [comment]
Without any code to help us help you, I'd say you ignored something async, but the docs of inert also do so maybe this needs a doc fix.

**Comment by kanongil** [comment]
@smahi You need to register the plugin before configuring the route.

**Comment by smahi** [comment]
@kanongil it works, thank you very much 👍 
I thought that the order does not matter .
